id: P1CDD1F68
initial_creation_type: ocr
source_metadata:
  volumes:
    0e55870b11754ca2aa0b5a1e7bbbf031:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: ཐུགས་རྗེ་ཆེན་པོ་ལ་སྨྲེ་སྔགས་ཀྱིས་བསྟོད་པ།
      total_pages: 1379
      volume_number: 37
